### ISSUE TITLE
Add OAuth2 authentication support

### ISSUE THREAD

**Issue by joincamp** [Narcolapser/python-o365#16]
In order to allow a shared usage of this library (webapps), I suggest using [Microsoft's OAuth workflow](https://msdn.microsoft.com/en-us/office/office365/howto/common-app-authentication-tasks) for authentication.

**Comment by Narcolapser** [comment]
While I agree with you I'm not entirely certain I can do this without having access to an Azure AD, which I do not. I'm not a webapp developer so OAuth is not something I'm very familiar with. Mind elaborating a little on what you imagine this would look like?

**Comment by joincamp** [comment]
If you really want this feature I can help with it. I can't say that I particularly have a need for it, so you might want to follow YAGNI and wait until someone votes and says that they need this feature. I'm not actually a user, just trying to give some feedback. Do you still want some direction?

**Comment by Narcolapser** [comment]
Ah, thanks for the feedback then. It is much appreciated. Like I mentioned in my reddit post this is my first project that has been worth note. So I am still trying to figure out how much features like these are things I /must/ do if I want this project to take off or not. I'm going to leave this for now and focus on some of the features that I was wanting, such as OneDrive files, and may come back to this later.

**Comment by Narcolapser** [comment]
Two examples I found of OAuth in use:
* [python_clientcred](https://github.com/jasonjoh/python_clientcred)
* [pythoncontacts](https://github.com/jasonjoh/pythoncontacts)

Something I've considered doing is refactoring how Authentication works in O365 in general. Rather than having to pass auth around from class to class have, have an Auth class which would wrap requests and deal with authentication, be it OAuth2 or (Username,Password). Does that sound insane or like a reasonable idea to you?

**Comment by roycem90** [comment]
Party Time, this is available in the latest code, give it a try

**Comment by olaor** [comment]
This works for me. I guess this issue could be closed?

**Comment by Narcolapser** [comment]
Thank you all.
