### ISSUE TITLE
Marking the Calendar as 'free' instead of 'Busy'

### ISSUE THREAD

**Issue by inform2amit** [Narcolapser/python-o365#53]
I do not see any option to setup location in the  Calendar/Event APIs. Also I need to  mark the calendar as 'free' for people in the group . These two features are highly recommended. If already there please let me know how to use them

**Comment by Narcolapser** [comment]
Sorry for the delay. I've had a few busy weeks. Anyway. Can you put the marking as free as a separate issue? Location and marking as free will most likely aren't related.

As to the location option. I'll try to look into that now. It shouldn't actually be to hard to implement since it is just adding a couple bits to the event JSON.

**Comment by Narcolapser** [comment]
I added a potential fix for the location bit. I don't actually have an account right now to test it (the other reason for my delay) so I can't actually be sure it works. Give it a try and let me know what happens. Cheers.

**Comment by Narcolapser** [comment]
hey @inform2amit did this fix your problem?

**Comment by Narcolapser** [comment]
I'm going to assume this problem is fixed.
