### ISSUE TITLE
Embedding Images

### ISSUE THREAD

**Issue by Thessentials** [Narcolapser/python-o365#56]
Hello, just started using your package and it's great! Very straightforward. However, I was wondering if it's possible to embed an image in an email using this package. If so, what would the code look like?

Thank you!

**Comment by Narcolapser** [comment]
The short answer is I am pretty sure yes. But I'll have to get back to you on the details. The basic idea is to set the content type to html, done [here](https://github.com/Narcolapser/python-o365/blob/92f8b27798d014bcfcb6bbfadcec22520bfddf9c/O365/message.py#L236) and then put in a normal HTML image tag. What I'm not sure about is what the href attribute of that tag would be.

**Comment by Thessentials** [comment]
Just tried it out and <img src="your image url"> seems to work. Thanks again!

**Comment by Narcolapser** [comment]
I had left this open because I wanted to figure out how to get this working using attachments. The process doesn't not sound particularly simple, a brief over view of how it works and some alternatives (one of which was mentioned above, simply linking the image) can be found [here](https://sendgrid.com/blog/embedding-images-emails-facts/). 

Because this library is about sending content, not crafting content, I don't intend to add the ability to do the above. You can do the Base64 encoding and the linking approach without any extra effort from this library so I recommend those if you need it.

**Comment by janscas** [comment]
The library now supports inline images. Check readme.
