### ISSUE TITLE
Attachments download problem

### ISSUE THREAD

**Issue by sergiownd** [Narcolapser/python-o365#58]
Hi, im new on the library and im developing and app that downloads a mail attachment. Everything goes correct in the way of selecting the mail, but when I use:
     m.fetchAttachments()
Nothing happends. If tryed to print it, and it gives me the size of the attachment. But im not able to download it?
Any help?

Thanks

**Comment by Narcolapser** [comment]
Welcome! I'm glad to see you using it. That is just the kind of thing I had in mind when I wrote this library.

So a little explination of how this works. When you get the emails from the API it does not include the attachments, it just includes references to them. The fetchAttachments function caches them locally so you can work with them. So there is one more step after you fetch the attachment to actually saving it. Why did I do it this way? Because some times you don't need to save it, some times you are meerly re-attaching it to a different message, like a reply or a forward. So try this:

``` python

m.fetchAttachments()
for att in m.attachments:
    att.save("path-to-folder")

```

**Comment by Narcolapser** [comment]
Did this help @sergiownd ?

**Comment by sergiownd** [comment]
Hei @Narcolapser sorry for no answer earlier.

Yep this worked perfect. Thank you so much :)
